### PR TITLE
Debug

### PR DESCRIPTION
**Pull request by alexrudd2**
See if we can have more light into https://github.com/numat/controllers/issues/1346

Remake of #17 because @juli4nb4dillo  forgot to check "Allow Edits by maintainers" :(

### CODE REVIEW

**Comment by juli4nb4dillo** [comment]
Where was I supposed to check?

**Comment by alexrudd2** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by juli4nb4dillo** [comment]
Oooh, so you could push on my repo, got it, I was lost.

**Comment by alexrudd2** [comment]
Closing in favor of https://github.com/numat/watlow/pull/45

**Pull request closed without merging**
